### ISSUE TITLE
Display saved recipes

### ISSUE THREAD

**Issue by Hifishbone** [QuinnPucci/what-to-eat#17]
We have 2 {itemName: itemDict} in localSotrage.
When displaying the save recipes,  there should be a table with two cols(MEAL, DRINK), and each col fills with buttons, each button shows the name of an item, each button should have an id = itemName.
When we click on the button, it will show the modal, by calling displayMeal(itemDict)/displayDrink(itemDict)

**Comment by QuinnPucci** [comment]
done everything except stuck on these 2 things:

-passing through saved recipe data as an argument when calling displayMeal or displayDrink function
-displaying recipe name as buttons text
